package olivetv

import (
	"errors"
	"regexp"
	"sort"
	"time"

	"github.com/imroc/req/v3"
	jsoniter "github.com/json-iterator/go"
	"github.com/tidwall/gjson"
)

func init() {
	registerSite("kuaishou", &kuaishou{})
}

type kuaishou struct {
	base
}

func (this *kuaishou) ID() SiteID {
	return "kuaishou"
}

func (this *kuaishou) Name() string {
	return "快手"
}

func (this *kuaishou) Snap(tv *TV) (err error) {
	tv.Info = &Info{
		Timestamp: time.Now().Unix(),
	}
	return this.set(tv)
}

func (this *kuaishou) set(tv *TV) error {
	// api := "https://live.kuaishou.com/u/ff2523341061"
	api := "https://live.kuaishou.com/u/" + tv.RoomID
	resp, err := req.R().
		SetHeaders(map[string]string{
			HeaderUserAgent: CHROME,
			HeaderCookie:    tv.cookie,
		}).
		Get(api)
	if err != nil {
		return err
	}

	re := regexp.MustCompile(`<script>window.__INITIAL_STATE__=([\s\S]*?);\(function`)
	caps := re.FindStringSubmatch(resp.String())
	if len(caps) < 2 {
		return nil
	}

	text := caps[1]

	tv.roomName = gjson.Get(text, "liveroom.liveStream.caption").String()
	tv.streamerName = gjson.Get(text, "liveroom.author.name").String()

	tv.roomOn = gjson.Get(text, "liveroom.isLiving").Bool()
	// fmt.Println("tv.roomOn", tv.roomOn)
	if !tv.roomOn {
		return nil
	}

	var ag KuaishouAutoGenerated
	jsoniter.UnmarshalFromString(text, &ag)
	playUrls := ag.Liveroom.LiveStream.PlayUrls
	if len(playUrls) == 0 {
		return errors.New("kuaishou: empty playUrls")
	}
	cands := playUrls[0].AdaptationSet.Representation
	if len(cands) == 0 {
		return errors.New("kuaishou: empty cands")
	}
	sort.Slice(cands, func(i, j int) bool {
		return cands[i].Bitrate > cands[j].Bitrate
	})
	tv.streamURL = cands[0].URL

	return nil
}

type KuaishouAutoGenerated struct {
	Liveroom struct {
		LiveStream struct {
			PlayUrls []struct {
				AdaptationSet struct {
					Representation []struct {
						URL     string `json:"url"`
						Bitrate int    `json:"bitrate"`
					} `json:"representation"`
				} `json:"adaptationSet"`
			} `json:"playUrls"`
		} `json:"liveStream"`
	} `json:"liveroom"`
}
